name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
  # Runs at 12:00 UTC every day
  - cron: '0 12 * * *'
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: mjoel4708/mjoel4708@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_EDITORS: true
          SHOW_LANGUAGES: true
