name: Waka - Readme
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master
jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Waka - Readme
        uses: athul/waka-readme@v0.1.8
        with:
          # GitHub access token with Repo scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Your Wakatime/Wakapi/Hakatime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Alternative API base URL when using a third-party WakaTime-ish backend
          API_BASE_URL: https://wakatime.com/api
          # Your GitHub repository
          REPOSITORY: your-github-repository
          # Add a commit message of your choice
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          # Displays the week number and days in Readme as title
          SHOW_TITLE: true
          # Section name for data to appear in readme
          SECTION_NAME: waka
          # Add the progress blocks of your choice
          BLOCKS: ░▒▓█
          # Time range of the queried statistics
          TIME_RANGE: last_7_days
          # Maximum number of languages to be shown
          LANG_COUNT: 5
          # Displays the amount of time spent for each language
          SHOW_TIME: true
          # Displays total coding time
          SHOW_TOTAL: false
          # Displays total coding time including unclassified languages
          SHOW_MASKED_TIME: false
